name: dev
base: ubuntu@22.04
sdks:
  - name: project-sdkcraft
scripts:
  format: |
    uv run ruff check --fix
    uv run ruff format
    uv run codespell --toml pyproject.toml --write-changes
  lint: |
    uv run ruff check
    uv run ruff format --diff
    uv run codespell --toml pyproject.toml
    uv run mypy --show-traceback --show-error-codes sdkcraft
    uv run pyright
    git ls-files | file --mime-type -Nnf- | grep shellscript | cut -f1 -d: | xargs -r shellcheck
    uv build --quiet .
    uv run twine check dist/*
    uv run yamllint .
  test: uv run pytest tests/unit
  integration: uv run --group "dev-$(lsb_release -cs)" pytest tests/integration
