name: dev
base: ubuntu@24.04
sdks:
  - name: uv
    channel: 24.04/edge
  - name: node
    channel: 24.04/edge
  - name: project-sdkcraft
actions:
  format: uv run make format
  lint: uv run make lint
  test: uv run --group "dev-$(lsb_release -cs)" pytest tests/unit "$@"
  integration: uv run --group "dev-$(lsb_release -cs)" pytest tests/integration "$@"
