#!/usr/bin/bash

# NOTE: we use apt-get instead of apt for non-interactive package installation.
# apt will prompt services restart for some of the packages below which will
# make the SDK installation stall forever.

# Update package list
apt-get -y update

# Ensure the Ubuntu Universe repos are enabled
apt-get -y install software-properties-common
add-apt-repository universe

# Install Python 3.11
apt-get -y update
apt-get -y install python3.11 python3.11-dev python3.11-venv

# Create working directory
sudo -u workshop -- mkdir -p /home/workshop/my_python_work/
