name: sdkcraft
version: 0.1.14
base: core24
summary: Design and build SDKs for Workshop
description: |
  A tool to design and build SDKs. An SDK can be defined
  as a set of components (parts), interfaces and hooks that SDKcraft will bundle
  together as a single package installable by Workshop.
confinement: classic
license: GPL-3.0-only
compression: lzo

apps:
  sdkcraft:
    command: bin/sdkcraft
    environment:
      PATH: ${SNAP}/bin:${SNAP}/usr/bin:${PATH}
  publish:
    environment:
      PATH: ${SNAP}/bin:${PATH}
    command: bin/publish.sh
parts:
  sdkcraft-libs:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - binutils
      - gpg
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-minimal
      - python3.12-minimal
      - python3-apt
      - shellcheck
      - zstd
    prime:
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/doc
    override-build: |
      ${SNAP}/libexec/snapcraft/craftctl default

      $CRAFT_PART_INSTALL/usr/bin/python3 -m compileall -q -j $CRAFT_PARALLEL_BUILD_COUNT $CRAFT_PART_INSTALL/usr/lib
  sdkcraft:
    source: .
    plugin: uv
    build-snaps:
      - astral-uv
    override-build: |
      ${SNAP}/libexec/snapcraft/craftctl default

      # Enable system-site-packages and fix interpreter path for subsequent build commands
      uv venv --allow-existing --python $CRAFT_STAGE/usr/bin/python3 --relocatable --system-site-packages $CRAFT_PART_INSTALL
    build-attributes:
      - enable-patchelf
    build-environment:
      - UV_COMPILE_BYTECODE: "1"
    after:
      - sdkcraft-libs
  python:
    plugin: nil
    after:
      - sdkcraft
    override-prime: |
      # Fix interpreter path for the installed snap.
      ln -sf ../usr/bin/python3 $CRAFT_PRIME/bin/python
  scripts:
    plugin: dump
    source: sdkcraft
    stage:
      - bin/*.sh
    organize:
      "*.sh": bin/
    build-attributes:
      - no-patchelf
  spread:
    plugin: go
    source: https://github.com/jonathan-conder/spread.git
    source-commit: 59b96df7eb19df72a448a917e72895f1668996aa
    build-snaps:
      - go/latest/stable
    build-attributes:
      - enable-patchelf
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: -trimpath '-ldflags=-w -s'
    stage:
      - -bin/humbox
    organize:
      bin/spread: bin/craft.spread
  yq:
    plugin: go
    source: https://github.com/mikefarah/yq.git
    source-tag: v4.44.1
    build-snaps:
      - go/latest/stable
    build-environment:
      - CGO_LDFLAGS_ALLOW: ".*"
    override-build: |
      CGO_ENABLED=0  go build -o "${CRAFT_PART_INSTALL}/bin/yq" -ldflags "-s -w" .
