name: sdkcraft
version: 0.1.9
base: core24
summary: Design and build SDKs for Workshop
description: |
  A tool to design and build SDKs. An SDK can be defined
  as a set of components (parts), interfaces and hooks that SDKcraft will bundle
  together as a single package installable by Workshop.
confinement: classic
grade: devel
license: GPL-3.0-only
compression: lzo

apps:
  sdkcraft:
    command: bin/python3 -m sdkcraft
    environment:
      PATH: ${SNAP}/bin:${SNAP}/usr/bin:${PATH}
      PYTHONPATH: ${SNAP}/lib/python3.12/dist-packages:${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}
  publish:
    environment:
      PATH: ${SNAP}/bin:${PATH}
      PYTHONPATH: ${SNAP}/lib/python3.12/dist-packages:${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}
    command: bin/publish.sh
parts:
  sdkcraft-libs:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - binutils
      - gpg
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-minimal
      - python3.12-minimal
      - python3-apt
      - zstd
    prime:
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/doc
  sdkcraft:
    source: .
    plugin: uv
    build-snaps:
      - astral-uv
    override-build: |
      craftctl default
      rm $CRAFT_PART_INSTALL/bin/python*
      ln -s ../usr/bin/python3 $CRAFT_PART_INSTALL/bin/python3
      ln -s python3 $CRAFT_PART_INSTALL/bin/python
    build-attributes:
      - enable-patchelf
    build-environment:
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
    after:
      - sdkcraft-libs
  scripts:
    plugin: dump
    source: sdkcraft
    organize:
      "*.sh": bin/
    build-attributes:
      - no-patchelf
  yq:
    plugin: go
    source: https://github.com/mikefarah/yq.git
    source-tag: v4.44.1
    build-snaps:
      - go/latest/stable
    build-environment:
      - CGO_LDFLAGS_ALLOW: ".*"
    override-build: |
      CGO_ENABLED=0  go build -o "${CRAFT_PART_INSTALL}/bin/yq" -ldflags "-s -w" .
