name: LXD Candidate Check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-snap:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - uses: actions/checkout@v6

      - uses: canonical/action-build@v1
        id: snapcraft

      - name: Upload snap artifact
        uses: actions/upload-artifact@v6
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
  snap-tests:
    needs: [build-snap]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: [self-hosted, linux, jammy, x64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@v1
        with:
          channel: 6/candidate
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout SDKcraft
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: false
      - name: Install spread
        run: |
          # go install is not supported for forks...
          git clone https://github.com/dmitry-lyfar/spread
          pushd spread
          go install ./...
          popd
      - name: Download snap artifact
        uses: actions/download-artifact@v7
        with:
          name: snap
          path: tests
      - name: Override LXD channel
        run: |
          cat <<EOF >>tests/spread/.env
          LXD_CHANNEL='6/candidate'
          EOF
      - name: Run spread
        run: spread ${{matrix.os}}:tests/spread/
