name: Check policy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-scans:
    name: Security scan
    uses: canonical/starflow/.github/workflows/scan-python.yaml@main
    with:
      uv-export-extra-args: ""
