name: QA
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: canonical/starflow/.github/workflows/lint-python.yaml@main
  test:
    uses: canonical/starflow/.github/workflows/test-python.yaml@main
    with:
      fast-test-platforms: '["self-hosted-linux-amd64-noble-medium"]'
      fast-test-python-versions: '["3.12"]'
      slow-test-platforms: '["self-hosted-linux-amd64-noble-medium"]'
      slow-test-python-versions: '["3.12"]'
      lowest-python-platform: self-hosted-linux-amd64-noble-medium
      lowest-python-version: "3.12"
