name: Release snap
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'arm64' && 'self-hosted-linux-arm64-noble-xlarge' || 'self-hosted-linux-amd64-noble-xlarge' }}
    steps:
      - uses: actions/checkout@v6

      - uses: canonical/action-build@v1
        id: snapcraft

      - uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-${{ matrix.arch }}
          path: ${{ steps.snapcraft.outputs.snap }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download amd64 snap
        uses: actions/download-artifact@v4
        with:
          name: snap-amd64
          path: snaps/

      - name: Download arm64 snap
        uses: actions/download-artifact@v4
        with:
          name: snap-arm64
          path: snaps/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: snaps/*.snap

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Generate CLI reference docs
        run: uv run python gendocs.py docs/

      - name: Check for changes, commit, and create PR if any
        run: |
          if git diff --exit-code; then
            echo "No changes detected, skipping commit and PR creation."
          else
            pr_branch="docs/reference-cli-$(date +'%Y%m%d%H%M%S')"
            git checkout -b $pr_branch

            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            git add .
            git commit -m "Update CLI reference docs"
            git push --set-upstream origin $pr_branch

            gh pr create --title "Update CLI reference docs" --body "This PR updates the generated CLI reference documentation." --base main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
