name: End to end tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

# Cancel currently-running builds when pushing new commits to a PR or branch
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-snap-amd64:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - uses: actions/checkout@v7

      - uses: canonical/action-build@v1
        id: snapcraft

      - name: Upload snap artifact
        uses: actions/upload-artifact@v7
        with:
          name: snap-amd64
          path: ${{ steps.snapcraft.outputs.snap }}
  build-snap-arm64:
    runs-on:
      - self-hosted
      - Linux
      - noble
      - ARM64
      - medium
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - uses: actions/checkout@v7

      - uses: canonical/action-build@v1
        id: snapcraft

      - name: Upload snap artifact
        uses: actions/upload-artifact@v7
        with:
          name: snap-arm64
          path: ${{ steps.snapcraft.outputs.snap }}
  snap-tests:
    needs: [build-snap-amd64, build-snap-arm64]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: [self-hosted, Linux, jammy, X64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@v1
        with:
          channel: 6/stable
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout SDKcraft
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26"
          cache: false
      - name: Install spread
        run: |
          # go install is not supported for forks...
          git clone https://github.com/dmitry-lyfar/spread
          pushd spread
          go install ./...
          popd
      - name: Download snap artifact
        uses: actions/download-artifact@v8
        with:
          name: snap-amd64
          path: tests
      - name: Run spread
        run: spread ${{ matrix.os }}:tests/spread/
      - name: Run store spread
        if: github.event_name != 'pull_request'
        env:
          SDKCRAFT_STORE_CREDENTIALS_PROD: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS_PROD }}
        run: spread ${{ matrix.os }}:tests/spread/store/
  publish:
    needs: [build-snap-amd64, build-snap-arm64, snap-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: amd64
            snap: ${{ needs.build-snap-amd64.outputs.snap }}
          - architecture: arm64
            snap: ${{ needs.build-snap-arm64.outputs.snap }}
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v8
        with:
          name: snap-${{ matrix.architecture }}
      - uses: canonical/action-publish@v1
        if: >-
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
        with:
          snap: ${{ matrix.snap }}
          release: edge/${{ github.event.pull_request.number }}
      - uses: canonical/action-publish@v1
        if: github.event_name == 'push'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
        with:
          snap: ${{ matrix.snap }}
          release: edge
