name: Unit and integration tests
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"
      - name: Configure environment
        run: |
          echo "::group::Begin snap install"
          echo "Installing snaps in the background while running apt and pip..."
          sudo snap install --no-wait shellcheck
          echo "::endgroup::"
          echo "::group::Wait for snap to complete"
          snap watch --last=install
          echo "::endgroup::"
      - name: Install dependencies by uv
          uv venv --system-site-packages
          uv sync
      - name: Run codespell
        run: make test-codespell
      - name: Run ruff
        run: make test-ruff
      - name: Run my-py
        run: make test-mypy
      - name: Run pyright
        run: make test-pyright
      - name: Run shellcheck
        run: make test-shellcheck
      - name: Run yamllint
        run: make test-yamllint
  tests:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"
      - name: Configure environment
        run: |
          echo "::group::apt-get update"
          sudo apt-get update
          echo "::endgroup::"
          echo "::group::apt-get install..."
          sudo apt-get install -y python3 python3-pip python3-apt python3-dev libapt-pkg-dev
          echo "::endgroup::"
      - name: Install dependencies by uv
        run: |
          uv venv --system-site-packages
          uv sync
      - name: Run unit tests
        run: |
          make test-units
      - name: Run integration tests
        run: |
          make test-integrations
